### PR TITLE
Use operators

### PR DESCRIPTION
**Pull request by nicktimko**
Python added a *brand new operator* `@` to the language because using `.dot()` was a pain in Numpy. Not sure why the regression towards methodizing everything.

### CODE REVIEW

**Comment by juliangaal** [comment]
I didn't label it correctly. The operators are meant for Matrix operations, not normal ones. You are talking about non-matrix operations, right?

**Comment by nicktimko** [comment]
`np.add(a, b)` is exactly equivalent to `a + b` if `a` or `b` are arrays, likewise for mul/divide. The `@`/`matmul` is the only non-elementwise operator, but it's then listed as being matrix multiplication.

**Comment by juliangaal** [comment]
ok. I'll test in the next couple of days

**Comment by marzoukh** [comment]
i'm new can help my

**Comment by juliangaal** [comment]
Added your suggestions. Couldn't use your pr directly, wanted to leave old option in there. thanks

**Pull request closed without merging**
