### PR TITLE
Add examples and installation guide

### PR DESCRIPTION
**Pull request by Nifled**
Added examples for some of the array and stats methods (following the format you used for the code). Also, I think there was a some typos in the operator column in Basic Statistics, so I fixed that too... correct me if I'm wrong. 

I also did a simple installation guide for installing al packages and installing each package individually.

### CODE REVIEW

**Comment by juliangaal** [comment]
Thanks dude! I appreciate it! Will add "How to install Python instructions" on the main README in the future as well

**Comment by Nifled** [comment]
Was there something wrong? Don't understand why it was removed.

**Comment by juliangaal** [comment]
hey man, mixed up some stuff and haven't had the chance to get it back up. Will be back up by the end of the week! homework is killing me :D

**Comment by juliangaal** [comment]
could you make a new pull request/do you have a backup? Otherwise, I'll re-add it manually

**Comment by Nifled** [comment]
I do! and I sure can, I'll send a PR soon.

**Comment by juliangaal** [comment]
Thanks. Sry again, I think I knew when this happened...I disregarded a warning and push with '--force' because I was to lacy to check for differences...

**Pull request merged**
